src/Entity/Chantier.php
<?php

namespace App\Entity;

use App\Repository\ChantierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Entity\Tache;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Persistence\Event\LifecycleEventArgs;

#[ORM\Entity(repositoryClass: ChantierRepository::class)]
class Chantier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'chantiersDiriges', targetEntity: Employe::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Employe $chef_de_chantier = null;

    /**
     * @var Collection<int, Tache>
     */
    #[ORM\OneToMany(targetEntity: Tache::class, mappedBy: 'chantier')]
    private Collection $taches;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_fin = null;

    #[ORM\ManyToOne(inversedBy: 'chantiers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_tache_suivante = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_de_la_voie = null;

    #[ORM\Column(length: 255)]
    private ?string $type_de_voie = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle_de_la_voie = null;

    #[ORM\Column]
    private ?int $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column(length: 255)]



    public function __construct()
    {
        $this->taches = new ArrayCollection();
        $this->date_tache_suivante = $this->date_de_debut;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChefDeChantier(): ?Employe
    {
        return $this->chef_de_chantier;
    }

    public function setChefDeChantier(?Employe $chef_de_chantier): static
    {
        $this->chef_de_chantier = $chef_de_chantier;

        return $this;
    }

    /**
     * @return Collection<int, Tache>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): static
    {
        if (!$this->taches->contains($tach)) {
            $this->taches->add($tach);
            $tach->setChantier($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): static
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getChantier() === $this) {
                $tach->setChantier(null);
            }
        }

        return $this;
    }

    public function getDateDeDebut(): ?\DateTimeInterface
    {
        return $this->date_de_debut;
    }

    public function setDateDeDebut(\DateTimeInterface $date_de_debut): static
    {
        $this->date_de_debut = $date_de_debut;

        return $this;
    }

    public function getDateDeFin(): ?\DateTimeInterface
    {
        return $this->date_de_fin;
    }

    public function setDateDeFin(\DateTimeInterface $date_de_fin): static
    {
        $this->date_de_fin = $date_de_fin;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateTacheSuivante(): ?\DateTimeInterface
    {
        return $this->date_tache_suivante;
    }

    public function setDateTacheSuivante(\DateTimeInterface $date_tache_suivante): static
    {
        $this->date_tache_suivante = $date_tache_suivante;

        return $this;
    }

    public function getNumeroDeLaVoie(): ?string
    {
        return $this->numero_de_la_voie;
    }

    public function setNumeroDeLaVoie(string $numero_de_la_voie): static
    {
        $this->numero_de_la_voie = $numero_de_la_voie;

        return $this;
    }

    public function getTypeDeVoie(): ?string
    {
        return $this->type_de_voie;
    }

    public function setTypeDeVoie(string $type_de_voie): static
    {
        $this->type_de_voie = $type_de_voie;

        return $this;
    }

    public function getLibelleDeLaVoie(): ?string
    {
        return $this->libelle_de_la_voie;
    }

    public function setLibelleDeLaVoie(string $libelle_de_la_voie): static
    {
        $this->libelle_de_la_voie = $libelle_de_la_voie;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updateStatut(LifecycleEventArgs $args): void
    {
        $now = new \DateTime();
        if ($this->date_de_debut > $now) {
            $this->statut = 'À venir';
        } elseif ($this->date_de_debut <= $now && $this->date_de_fin >= $now) {
            $this->statut = 'En cours';
        } else {
            $this->statut = 'Terminé';
        }
    }
}

src/Form/ChantierType.php
<?php

namespace App\Form;

use App\Entity\Chantier;
use App\Entity\Client;
use App\Entity\Employe;
use App\Repository\EmployeRepository;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChantierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom du chantier :',
                'attr' => [
                    'placeholder' => 'Nom du chantier',
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('numero_de_la_voie', TextType::class, [
                'label' => 'Numéro de la voie :',
                'attr' => [
                    'placeholder' => 'Numéro de la voie',
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('type_de_voie', ChoiceType::class,
                [
                    'label' => 'Type de voie :',
                    'choices' => [
                        'Rue' => 'Rue',
                        'Avenue' => 'Avenue',
                        'Boulevard' => 'Boulevard',
                        'Impasse' => 'Impasse',
                        'Place' => 'Place',
                        'Route' => 'Route',
                        'Chemin' => 'Chemin',
                        'Allée' => 'Allée',
                        'Passage' => 'Passage',
                        'Quai' => 'Quai',
                        'Square' => 'Square',
                        'Cours' => 'Cours',
                        'Rond-Point' => 'Rond-Point',
                        'Hameau' => 'Hameau',
                        'Lotissement' => 'Lotissement',
                        'Parvis' => 'Parvis',
                        'Promenade' => 'Promenade',
                        'Villa' => 'Villa']
                    ]

            )
            ->add('libelle_de_la_voie', TextType::class, [
                'label' => 'Libellé de la voie :',
                'attr' => [
                    'placeholder' => 'Libellé de la voie',
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('code_postal', NumberType::class, [
                'label' => 'Code postal :',
                'attr' => [
                    'placeholder' => 'Code postal',
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('ville', TextType::class, [
                'label' => 'Ville :',
                'attr' => [
                    'placeholder' => 'Ville',
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('date_de_debut', null, [
                'label' => 'Date de début :',
                'widget' => 'single_text',
            ])
            ->add('date_de_fin', null, [
                'label' => 'Date de fin :',
                'widget' => 'single_text',
            ])
            ->add('chef_de_chantier', EntityType::class, [
                'label' => 'Chef de chantier :',
                'class' => Employe::class,
                'choice_label' => 'nom',
                'query_builder' => function (EmployeRepository $er) {
                    return $er->createQueryBuilder('e')
                              ->where('e.est_chef_de_chantier = :val')
                              ->setParameter('val', true);
                },
                'attr' => [
                    'class' => 'aaaaaa'
                ]
            ])
            ->add('client', EntityType::class, [
                'label' => 'Client :',
                'class' => Client::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chantier::class,
        ]);
    }
}

src/Controller/ChantierController.php
<?php

namespace App\Controller;

use App\Entity\Chantier;
use App\Form\ChantierType;
use App\Repository\ChantierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/chantier')]
final class ChantierController extends AbstractController
{
    #[Route(name: 'app_chantier_index', methods: ['GET'])]
    public function index(ChantierRepository $chantierRepository): Response
    {
        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantierRepository->findAll(),
        ]);
    }

    #[Route('/termine', name:'app_chantier_termine', methods: ['GET'])]
    public function chantier_fini(ChantierRepository $chantierRepository): Response
    {

        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantierRepository->findBy(['statut' => 'Terminé']),
        ]);
    }

    #[Route('/encours', name: 'app_chantier_en_cours', methods: ['GET'])]
    public function chantier_en_cours(ChantierRepository $chantierRepository): Response
    {   
        $chantiers = $chantierRepository->findBy(['statut' => 'En cours']);
        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantiers,
        ]);
    }

    #[Route('/avenir', name: 'app_chantier_a_venir', methods: ['GET'])]
    public function chantier_a_venir(ChantierRepository $chantierRepository): Response
    {
        $chantiers = $chantierRepository->findBy(['statut' => 'A venir']);
        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantiers,
        ]);
    }

    #[Route('/new', name: 'app_chantier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $chantier = new Chantier();
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($chantier);

            if ($chantier->getDateDeFin() <= $chantier->getDateDeDebut()) {
                $this->addFlash('error', 'La date de fin doit être supérieure à la date de début.');
                return $this->redirectToRoute('app_chantier_new');
            }

            if ($chantier->getDateDeDebut() < new \DateTime()) {
                $this->addFlash('error', 'La date de début doit être supérieure ou égale à la date actuelle.');
                return $this->redirectToRoute('app_chantier_new');
            }

            $chantier->setDateTacheSuivante($chantier->getDateDeDebut());
            $entityManager->flush();

            return $this->redirectToRoute('app_chantier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chantier/new.html.twig', [
            'chantier' => $chantier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chantier_show', methods: ['GET'])]
    public function show(Chantier $chantier): Response
    {
        return $this->render('chantier/show.html.twig', [
            'chantier' => $chantier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chantier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chantier $chantier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chantier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chantier/edit.html.twig', [
            'chantier' => $chantier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chantier_delete', methods: ['POST'])]
    public function delete(Request $request, Chantier $chantier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chantier->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($chantier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_chantier_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/chantier/_delete_form.html.twig
<form method="post" action="{{ path('app_chantier_delete', {'id': chantier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chantier.id) }}">
    <button class="btnSupprimer">
        <svg class="svg-icon icon-trash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c9.4-9.4 24.6-9.4 33.9 0l47 47 47-47c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-47 47 47 47c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-47-47-47 47c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l47-47-47-47c-9.4-9.4-9.4-24.6 0-33.9z"/></svg>
    </button>
</form>

templates/chantier/_form.html.twig
{{ form_start(form) }}
<div class="gridCol2">
    <div class="left-part">
        <div class="group1">
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom) }}
        </div>

        <div class="group1">
            {{ form_label(form.date_de_debut) }}
            {{ form_widget(form.date_de_debut) }}
        </div>

        <div class="group1">
            {{ form_label(form.date_de_fin) }}
            {{ form_widget(form.date_de_fin) }}
        </div>

        <div class="group1">
            {{ form_label(form.chef_de_chantier) }}
            {{ form_widget(form.chef_de_chantier) }}
        </div>

        <div class="group1">
            {{ form_label(form.client) }}
            {{ form_widget(form.client) }}
        </div>
    </div>

    <div class="right-part">
        <div class="group2">
            {{ form_label(form.numero_de_la_voie) }}
            {{ form_widget(form.numero_de_la_voie) }}
        </div>

        <div class="group2">
            {{ form_label(form.type_de_voie) }}
            {{ form_widget(form.type_de_voie) }}
        </div>

        <div class="group2">
            {{ form_label(form.libelle_de_la_voie) }}
            {{ form_widget(form.libelle_de_la_voie) }}
        </div>

        <div class="group2">
            {{ form_label(form.code_postal) }}
            {{ form_widget(form.code_postal) }}
        </div>

        <div class="group2">
            {{ form_label(form.ville) }}
            {{ form_widget(form.ville) }}
        </div>
    </div>
</div>

<button class="form-btn-add">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/chantier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Chantier{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Modifier le chantier</h1>
        <a class="BtnEmploye" href="{{ path('app_chantier_index') }}">Retour à la liste des chantiers</a>
    </div>

    <div class="FormNewEmploye">
        {{ include('chantier/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    </div>

{% endblock %}

templates/chantier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Chantiers{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Tous les chantiers</h1>
        <a class="BtnEmploye a-btn" href="{{ path('app_chantier_new') }}">+ Créer un chantier</a>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Responsable</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Adresse</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for chantier in chantiers %}
            <tr>
                <td>{{ chantier.id }}</td>
                <td>{{ chantier.nom }}</td>
                <td>{{ chantier.getChefDeChantier.getNom }}</td>
                <td>{{ chantier.dateDeDebut ? chantier.dateDeDebut|date('d/m/Y') : '' }}</td>
                <td>{{ chantier.dateDeFin ? chantier.dateDeFin|date('d/m/Y') : '' }}</td>
                <td>{{ chantier.numeroDeLaVoie }} {{ chantier.typeDeVoie }} {{ chantier.libelleDeLaVoie }}, {{ chantier.codePostal }}, {{ chantier.ville }}</td>
                <td>
                    <div class="ROW">
                        <a class="btn-preview" href="{{ path('app_chantier_show', {'id': chantier.id}) }}">
                            <svg class="svg-icon icon-show" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M288 80c-65.2 0-118.8 29.6-159.9 67.7C89.6 183.5 63 226 49.4 256c13.6 30 40.2 72.5 78.6 108.3C169.2 402.4 222.8 432 288 432s118.8-29.6 159.9-67.7C486.4 328.5 513 286 526.6 256c-13.6-30-40.2-72.5-78.6-108.3C406.8 109.6 353.2 80 288 80zM95.4 112.6C142.5 68.8 207.2 32 288 32s145.5 36.8 192.6 80.6c46.8 43.5 78.1 95.4 93 131.1c3.3 7.9 3.3 16.7 0 24.6c-14.9 35.7-46.2 87.7-93 131.1C433.5 443.2 368.8 480 288 480s-145.5-36.8-192.6-80.6C48.6 356 17.3 304 2.5 268.3c-3.3-7.9-3.3-16.7 0-24.6C17.3 208 48.6 156 95.4 112.6zM288 336c44.2 0 80-35.8 80-80s-35.8-80-80-80c-.7 0-1.3 0-2 0c1.3 5.1 2 10.5 2 16c0 35.3-28.7 64-64 64c-5.5 0-10.9-.7-16-2c0 .7 0 1.3 0 2c0 44.2 35.8 80 80 80zm0-208a128 128 0 1 1 0 256 128 128 0 1 1 0-256z"/></svg>
                        </a>
                        <a class="btn-edit" href="{{ path('app_chantier_edit', {'id': chantier.id}) }}">
                            <svg class="svg-icon icon-edit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1 0 32c0 8.8 7.2 16 16 16l32 0zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z"/></svg>
                        </a>
                        {{ include('chantier/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Il n'y a aucun chantiers référencés pour le moment.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/chantier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Chantier{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Créer un nouveau chantier</h1>
        <a class="BtnEmploye a-btn" href="{{ path('app_chantier_index') }}">Retour à la liste</a>
    </div>

    <div class="FormNewEmploye">
        {{ include('chantier/_form.html.twig') }}
    </div>


{% endblock %}

templates/chantier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chantier{% endblock %}

{% block body %}

    <div class="ROW">
        <h1 class="TitlePage">Chantier - {{ chantier.nom }}</h1>
        <a class="BtnEmploye" href="{{ path('app_chantier_index') }}">Retour à la liste</a>
        <a href="{{ path('app_chantier_edit', {'id': chantier.id}) }}"><img class="btnListe btnListeModifView" src="../../Image/modif.png"></a>
    </div>


    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ chantier.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ chantier.nom }}</td>
            </tr>
            <tr>
                <th>Responsable</th>
                <td>{{ chantier.getChefDeChantier.getNom }}</td>
            </tr>
            <tr>
                <th>Date de début</th>
                <td>{{ chantier.dateDeDebut ? chantier.dateDeDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date de fin</th>
                <td>{{ chantier.dateDeFin ? chantier.dateDeFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>
                    Adresse
                </th>
                <td>
                    <p id="adresse">32 rue des vignes, Cachan</p>
                </td>
            </tr>
        </tbody>
    </table>

    <h2 class="TitlePage">Tâches du chantier :</h2>
    <div class="gridCol2">
        <ul class="listeTache">
            {% for tache in chantier.taches %}

                <li>
                    <strong>{{ tache.description }}</strong>
                    ({{ tache.statut }})
                    <br> ➝ Durée : {{ tache.duree }} jour{% if tache.duree > 1 %}s{% endif %}
                    <br> 📅 Début : {{ tache.dateDeDebut ? tache.dateDeDebut|date('Y-m-d') : 'Non défini' }}
                    <br> ⏳ Fin : {{ tache.dateDeFin ? tache.dateDeFin|date('Y-m-d') : 'Non défini' }}
                </li>
                <hr>
            {% else %}
                <li><em>Aucune tâche</em></li>

            {% endfor %}
        </ul>
        <div id="map" style="height:300px;width:600px;"></div>
    </div>

{% endblock %}