src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column]
    private ?bool $est_chef_de_chantier = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Metier $metier = null;

    /**
     * @var Collection<int, Chantier>
     */
    #[ORM\OneToMany(mappedBy: 'chef_de_chantier', targetEntity: Chantier::class)]
    private Collection $chantiersDiriges;

    /**
     * @var Collection<int, Tache>
     */
    #[ORM\ManyToMany(targetEntity: Tache::class, mappedBy: 'employes')]
    private Collection $taches;

    #[ORM\Column]
    private ?bool $disponible = true;

    /**
     * @var Collection<int, Assignation>
     */
    #[ORM\OneToMany(mappedBy: 'employe', targetEntity: Assignation::class)]
    private Collection $assignations;

    public function __construct()
    {
        $this->taches = new ArrayCollection();
        $this->assignations = new ArrayCollection();
        $this->chantiersDiriges = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isEstChefDeChantier(): ?bool
    {
        return $this->est_chef_de_chantier;
    }

    public function setEstChefDeChantier(bool $est_chef_de_chantier): static
    {
        $this->est_chef_de_chantier = $est_chef_de_chantier;

        return $this;
    }

    /**
     * @return Collection<int, Chantier>
     */
    public function getChantiersDiriges(): Collection
    {
        return $this->chantiersDiriges;
    }

    public function addChantierDirige(Chantier $chantier): static
    {
        if (!$this->chantiersDiriges->contains($chantier)) {
            $this->chantiersDiriges->add($chantier);
            $chantier->setChefDeChantier($this);
        }

        return $this;
    }

    public function removeChantierDirige(Chantier $chantier): static
    {
        if ($this->chantiersDiriges->removeElement($chantier)) {
            if ($chantier->getChefDeChantier() === $this) {
                $chantier->setChefDeChantier(null);
            }
        }

        return $this;
    }

    public function getMetier(): ?Metier
    {
        return $this->metier;
    }

    public function setMetier(?Metier $metier): static
    {
        $this->metier = $metier;

        return $this;
    }

    /**
     * @return Collection<int, Tache>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): static
    {
        if (!$this->taches->contains($tach)) {
            $this->taches->add($tach);
            $tach->addEmploye($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): static
    {
        if ($this->taches->removeElement($tach)) {
            $tach->removeEmploye($this);
        }

        return $this;
    }

    public function isDisponible(): ?bool
    {
        return $this->disponible;
    }

    public function setDisponible(bool $disponible): static
    {
        $this->disponible = $disponible;

        return $this;
    }

    /**
     * @return Collection<int, Assignation>
     */
    public function getAssignations(): Collection
    {
        return $this->assignations;
    }

    public function addAssignation(Assignation $assignation): self
    {
        if (!$this->assignations->contains($assignation)) {
            $this->assignations[] = $assignation;
            $assignation->setEmploye($this);
        }
        return $this;
    }

    public function removeAssignation(Assignation $assignation): self
    {
        if ($this->assignations->removeElement($assignation)) {
            if ($assignation->getEmploye() === $this) {
                $assignation->setEmploye(null);
            }
        }
        return $this;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Metier;
use App\Entity\Tache;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', null, ['label' => 'Nom :'])
            ->add('prenom' , null, ['label' => 'Prénom :'])
            ->add('telephone' , null, ['label' => 'Téléphone :'])
            ->add('est_chef_de_chantier' , null, ['label' => 'Chef de chantier ?'])
            ->add('metier', EntityType::class, [
                'label' => 'Métier :',
                'class' => Metier::class,
                'choice_label' => 'label',
            ])
            ->add('disponible', ChoiceType::class, [
                'label' => 'Disponible :',
                'choices' => [
                    'Oui' => true,
                    'Non' => false,
                ],
                'required' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use App\Repository\EmployeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/employe')]
final class EmployeController extends AbstractController
{
    #[Route(name: 'app_employe_index', methods: ['GET'])]
    public function index(EmployeRepository $employeRepository): Response
    {
        return $this->render('employe/index.html.twig', [
            'employes' => $employeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_employe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $employe = new Employe();
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($employe);
            $entityManager->flush();

            return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employe/new.html.twig', [
            'employe' => $employe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employe_show', methods: ['GET'])]
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_employe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Employe $employe, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employe/edit.html.twig', [
            'employe' => $employe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employe_delete', methods: ['POST'])]
    public function delete(Request $request, Employe $employe, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employe->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($employe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employe/_delete_form.html.twig
<form method="post" action="{{ path('app_employe_delete', {'id': employe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employe.id) }}">
    <button class="btnSupprimer">
        <svg class="svg-icon icon-trash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c9.4-9.4 24.6-9.4 33.9 0l47 47 47-47c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-47 47 47 47c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-47-47-47 47c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l47-47-47-47c-9.4-9.4-9.4-24.6 0-33.9z"/></svg>
    </button>
</form>

templates/employe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="form-btn-add">{{ button_label|default("Ajouter") }}</button>
{{ form_end(form) }}

templates/employe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Employé{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Modifier l'employé</h1>
        <a class="BtnEmploye a-btn" href="{{ path('app_employe_index') }}">Retour à la liste des employés</a>
    </div>

    <div class="FormNewEmploye">
        {{ include('employe/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    </div>


{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employes{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Employés</h1>
        <a class="BtnEmploye a-btn" href="{{ path('app_employe_new') }}">+ Ajouter un employé</a>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Téléphone</th>
                <th>Profession</th>
                <th>Chef de chantier</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employe in employes %}
            <tr>
                <td>{{ employe.id }}</td>
                <td>{{ employe.nom }}</td>
                <td>{{ employe.prenom }}</td>
                <td>{{ employe.telephone }}</td>
                <td>{{ employe.getMetier.getLabel }}</td>
                <td>{{ employe.estChefDeChantier ? 'Oui' : 'Non' }}</td>
                <td>
                    <div class="ROW">
                        <a class="btn-preview" href="{{ path('app_employe_show', {'id': employe.id}) }}" class="btn btn-info btn-sm">
                            <svg class="svg-icon icon-show" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M288 80c-65.2 0-118.8 29.6-159.9 67.7C89.6 183.5 63 226 49.4 256c13.6 30 40.2 72.5 78.6 108.3C169.2 402.4 222.8 432 288 432s118.8-29.6 159.9-67.7C486.4 328.5 513 286 526.6 256c-13.6-30-40.2-72.5-78.6-108.3C406.8 109.6 353.2 80 288 80zM95.4 112.6C142.5 68.8 207.2 32 288 32s145.5 36.8 192.6 80.6c46.8 43.5 78.1 95.4 93 131.1c3.3 7.9 3.3 16.7 0 24.6c-14.9 35.7-46.2 87.7-93 131.1C433.5 443.2 368.8 480 288 480s-145.5-36.8-192.6-80.6C48.6 356 17.3 304 2.5 268.3c-3.3-7.9-3.3-16.7 0-24.6C17.3 208 48.6 156 95.4 112.6zM288 336c44.2 0 80-35.8 80-80s-35.8-80-80-80c-.7 0-1.3 0-2 0c1.3 5.1 2 10.5 2 16c0 35.3-28.7 64-64 64c-5.5 0-10.9-.7-16-2c0 .7 0 1.3 0 2c0 44.2 35.8 80 80 80zm0-208a128 128 0 1 1 0 256 128 128 0 1 1 0-256z"/></svg>
                        </a>
                        <a class="btn-edit" href="{{ path('app_employe_edit', {'id': employe.id}) }}" class="btn btn-info btn-sm">
                            <svg class="svg-icon icon-edit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1 0 32c0 8.8 7.2 16 16 16l32 0zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z"/></svg>
                        </a>
                        {{ include('employe/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Il n'y a aucun employés référencés pour le moment.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/employe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Employé{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Ajouter un employé</h1>
        <a class="BtnEmploye a-btn" href="{{ path('app_employe_index') }}">Retour à la liste des employés</a>
    </div>

    <div class="FormNewEmploye">
        {{ include('employe/_form.html.twig') }}
    </div>



{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employé{% endblock %}

{% block body %}
    <div class="ROW">
        <h1 class="TitlePage">Employé</h1>
        <a class="BtnEmploye" href="{{ path('app_employe_index') }}">Retour à la liste des employés</a>
        <a href="{{ path('app_employe_edit', {'id': employe.id}) }}"><img class="btnListe btnListeModifView" src="../../Image/modif.png"></a>
    </div>


    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ employe.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ employe.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ employe.prenom }}</td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ employe.telephone }}</td>
            </tr>
            <tr>
                <th>Prof.</th>
                <td>{{ employe.getMetier.getLabel }}</td>
            </tr>
            <tr>
                <th>Chef de chantier</th>
                <td>{{ employe.estChefDeChantier ? 'Oui' : 'Non' }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}